spring:
  application:
    name: user-service
  r2dbc:
    url: r2dbc:mysql://15.164.98.73:3306/holamuser?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    username: minjunkang
    password: alswnsrkdA1$

server:
  port: 4500

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://52.78.34.107:8761/eureka/

logging:
  level:
    org.springframework.r2dbc: DEBUG

dmoain:
  client:
    mountain:
      url: http://13.209.98.223:5000/

jwt:
  secret-key: aG9sYW0tcHJvamVjdC1zZWNyZXQta2V5LWNvZGVzdGF0ZQ==
  accessExpires:  7200000
  refreshExpires:  1210000000
