spring:
  application:
    name: user-service
  mail:
    host: smtp.gmail.com
    username: testsendmailgo@gmail.com
    password: xyvildycxxoisjjw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    port: 7500
  redis:
    host: 54.180.94.220
    port: 6379
    password: 123456
  r2dbc:
    url: r2dbc:mysql://15.164.98.73:3306/holamuser?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    username: minjunkang
    password: alswnsrkdA1$
  kafka:
    consumer:
      bootstrap-servers: 13.125.227.251:9092
      group-id: foo
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 13.125.227.251:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 4500

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://52.78.34.107:8761/eureka/

logging:
  level:
    org.springframework.r2dbc: DEBUG

domain:
  client:
    mountain:
      url: http://13.209.98.223:5000/

jwt:
  secret-key: aG9sYW0tcHJvamVjdC1zZWNyZXQta2V5LWNvZGVzdGF0ZQ==
  accessExpires:  7200000
  refreshExpires:  1210000000
